server:
  port: 8089 #应用端口
spring:
   redis:
    database: 2
    host: localhost
    port: 6379
    password: XqbSXMIThB6MyHWV
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  application:
    name: eureka-customer #应用名称
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    instance-id: eureka-customer-hystrix1 #自定义hystrix服务器名称相关名称
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8751/eureka/ #注册中心地址，若想做成集群，在service-url配置多个地址即可
feign:
  hystrix:
    enabled: true  
---
server:
  port: 8088 #应用端口
security:
  oauth2:
    client:
      client-id: test
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8090/oauth/authorize
      access-token-uri: http://localhost:8090/oauth/token
    resource:
      id: test
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8090/oauth/check_token  
spring:
   redis:
    database: 2
    host: localhost
    port: 6379
    password: XqbSXMIThB6MyHWV
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  application:
    name: eureka-customer #应用名称
  profiles: test
eureka:
  instance:
    prefer-ip-address: true
    instance-id: eureka-customer-hystrix1 #自定义hystrix服务器名称相关名称
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8751/eureka/ #注册中心地址，若想做成集群，在service-url配置多个地址即可
feign:
  hystrix:
    enabled: true  

    



